services:
  # mongo_db:
  #   image: mongo:latest
  #   container_name: db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - "mongo-data:/data/db"

  fastapi_app:
    build: ./app
    container_name: fastapi
    ports:
      - "8000:8000"
    # depends_on:
    #   - mongo_db
    env_file:
      - .env
    volumes:
      - ./app:/app

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend/auctionhub
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/auctionhub:/app
    command: ["npm", "run", "dev"]


volumes:
  app:
  # mongo-data:
