services:
  # mongo_db:
  #   image: mongo:latest
  #   container_name: db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - "mongo-data:/data/db"

  fastapi_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend/auctionhub
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend/auctionhub:/app:delegated
      - /app/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]



volumes:
  app:
  # mongo-data:
