# frontend/Dockerfile

FROM node:20-alpine

# Ustawiamy katalog roboczy w kontenerze
WORKDIR /app

# Kopiujemy tylko pliki konfiguracyjne npm, aby wykorzystać cache warstw
COPY package*.json ./

# Instalujemy zależności precyzyjnie zgodnie z lockfile
RUN npm ci --include=dev

# Kopiujemy resztę kodu aplikacji
COPY . .

# Otwieramy port, na którym działa Vite
EXPOSE 3000

# Domyślna komenda uruchamiająca aplikację
CMD ["npm", "run", "dev"]